language: node_js
node_js:
  - "20"
cache: npm
env:
  - CI=true
install: npm ci
script:
  - npm run test:ci
  - npm run lint
  - npm run build
  - npm run build-storybook
branches:
  only:
    - main
    - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: storybook-static
  on:
    branch: master
