name: CI

# 当发生 push代码/ pull request -> 运行 CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 测试和构建
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test:ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

  # 部署到 Storybook
  deploy-pages:
    needs: test-and-build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Upload artifact
        uses: actions/upload-pages-artifact@3
        with:
          path: storybook-static
  # 部署到 GitHub Pages
  deploy:
    needs: deploy-pages
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@4
