name: Publish components

on:
  push:
    tags:
      - "components-v*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Verify & build
        run: pnpm utils:build && pnpm release

      - name: Publish @aozi6666/bee-design
        working-directory: packages/components
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
